name: Coverage

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  coverage-linux:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y lcov
      - name: Check out \"${{ github.repository }}\", branch \"${{ github.ref }}\."
        uses: actions/checkout@v4
      - name: make coverage
        run: make coverage CI=1
